all:
	make -f down.mak
	make -f look.mak
	make -f Governor.mak
	make -f exit.mak
	make -f fresh.mak
	make -f start.mak
	make -f clear.mak

clean:
	make -f down.mak $@
	make -f look.mak $@
	make -f Governor.mak $@
	make -f exit.mak $@
	make -f fresh.mak $@
	make -f start.mak $@
	make -f clear.mak $@

